# TensorFlow程序设计模式

### TensorFlow 和 Keras的最大差别是，对于TensorFlow，我们必须自行设计张量（矩阵）运算

### TensorFlow 程序设计模式的核心是“计算图”，可分为两部分：建立“计算图”和执行“计算图”
![](./lesson15/2.jpg)

## 15.1 建立“计算图”

### 为了示范TensorFlow程序设计模式，建立简单的“计算图”，只有一个常数与一个变量。建立完成后再执行此“计算图”

In [1]:
# 1 导入tensorflow 模块
import tensorflow as tf

F:\python\Anaconda3\envs\tensorFLow-gpu\lib\site-packages\tensorflow\python\framework\dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
F:\python\Anaconda3\envs\tensorFLow-gpu\lib\site-packages\tensorflow\python\framework\dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
F:\python\Anaconda3\envs\tensorFLow-gpu\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
F:\python\Anaconda3\envs\tensorFLow-gpu\lib\site-packages\ten

In [2]:
# 2. 建立TensorFlow常数
ts_c = tf.constant(2, name='ts_c')#设置常数值为2， 设置常数名称为 ts_c，会显示在计算图上

In [3]:
# 3. 查看TensorFlow常数
ts_c

<tf.Tensor 'ts_c:0' shape=() dtype=int32>

- #### tf.Tensor: 代表这是TensorFlow张量
- #### shape=(): 代表这是零维的tensor，也即是数值
- #### dtype=int32: 代表此张量的类型是int32

In [4]:
# 4. 建立TensorFlow变量
ts_x = tf.Variable(ts_c+5, name='ts_x')

In [5]:
# 5. 查看TensorFlow变量
ts_x

<tf.Variable 'ts_x:0' shape=() dtype=int32_ref>

## 15.2 执行“计算图”

### 建立“计算图”后，就可以执行“计算图”。只是在执行前必须先建立Session（会话），在TensorFlow中Session代表客户端和执行设备之间建立的连接。有了这个连接，就可以在设备中执行“计算图”，后续任何与设备之间的沟通都必须通过这个Session，并可以取得执行后的结果

In [6]:
# 1 建立session， 使用tf.session() 建立Session对象 sess
sess = tf.Session()

In [7]:
# 2 初始化变量， 使用如下的执行初始化所有TensorFlow global变量
init = tf.global_variables_initializer()
sess.run(init)

In [8]:
# 3 使用session.run 显示TensorFlow常数
print('ts_c = ', sess.run(ts_c))

ts_c =  2


In [9]:
# 4 使用session.run 显示TensorFlow变量
print('ts_x = ', sess.run(ts_x))

ts_x =  7


In [11]:
# 5 使用.eval()方法显示TensorFlow常数（另一种执行TensorFlow“计算图”的方法是使用TensorFlow对象的eval()方法，使用此方法必须传入session参数）
print('ts_c = ', ts_c.eval(session=sess))

ts_c =  2


In [12]:
# 6 使用.eval()方法显示TensorFlow变量
print('ts_x = ', ts_x.eval(session=sess))

ts_x =  7


In [13]:
# 7 关闭TensorFlow的Session
sess.close()

In [1]:
# 8 将以上指令一起运行
import tensorflow as tf
ts_c = tf.constant(2, name='ts_c')
ts_x = tf.Variable(ts_c+5, name='ts_x')

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

print('ts_c = ', sess.run(ts_c))
print('ts_x = ', ts_x.eval(sess))
sess.close()

F:\python\Anaconda3\envs\tensorFLow-gpu\lib\site-packages\tensorflow\python\framework\dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
F:\python\Anaconda3\envs\tensorFLow-gpu\lib\site-packages\tensorflow\python\framework\dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
F:\python\Anaconda3\envs\tensorFLow-gpu\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
F:\python\Anaconda3\envs\tensorFLow-gpu\lib\site-packages\ten

ts_c =  2
ts_x =  7


In [ ]:
"""
9. With语句打开Session并自动关闭
在前面的步骤中，使用tf.Session()建立session，并且使用session.close()关闭session。这种做法可能存在一下问题
（1）可能忘记关闭Session
（2）当程序执行中发生异常，导致没办法关闭session。
为了解决此问题，可以使用With语句：
With关键词后面是建立的命令tf.Session(), as关键词后面是Session的变量sess。
在With程序块中可以使用sess变量与设备沟通，离开With程序块就自动关闭Session
"""

In [2]:
a = tf.constant(2, name='a')
b = tf.Variable(a+10, name='b')

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('a = ', sess.run(a))
    print('b = ', sess.run(b))
    print('b = ', b.eval(sess))

a =  2
b =  12
b =  12


## 15.3 TensorFlow placeholder

### 前面的范例中，在建立“计算图”时，我们会设置ts_c常数值为2，并设置变量ts_x为ts_c加5，这都是在建立“计算图”阶段就已经设置完成的。如果希望在执行“计算图”时才设置数值，就必须使用placeholder

In [4]:
"""
1. 建立“计算图”
以下建立两个placeholder,分别是width,height，然后使用tf.multiply将weight和height相乘，结果为area
"""
width = tf.placeholder('int32')
height = tf.placeholder('int32')
area = tf.multiply(width, height)

In [6]:
"""
2. 执行“计算图”
执行sess.run传入feed_dict参数{width:6, height:8}
"""
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('area = ', sess.run(area, feed_dict={width:6, height:8}))

area =  48


![](./lesson15/3.jpg)

## 15.4 TensorFlow数值运算方法介绍

![](./lesson15/4.jpg)

## 15.5 TensorBoard

### TensorFlow提供了TensorBoard，可以让我们以可视化的方式查看所建立的“计算图”。

In [8]:
"""
1.建立TensorFlow Variable变量
"""
width = tf.placeholder('int32', name='width')
height = tf.placeholder('int32', name='height')
area = tf.multiply(width, height, name='area')

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('area = ', sess.run(area, feed_dict={width:6, height: 8}))

area =  48


In [9]:
"""
2.建立TensorFlow Variable变量
将要显示在tensor board的数据写如log文件
"""
tf.summary.merge_all()    # 将所有要显示在TensorBoard中的数据整合
train_writer = tf.summary.FileWriter('log/area', sess.graph)    # 将所有要显示在TensorBoard中的数据写入log文件

### 在 tensorboard 中查看计算图，如下
![](./lesson15/5.jpg)

## 15.6 建立一维与二维张量

### 前面的章节中，使用了零维的张量，也就是标量（数值），接下来使用TensorFlow建立：一维的张量（向量），二维以上的张量称为[矩阵]

In [10]:
"""
1. 建立一维的张量（向量）
建立一维的张量（tensor）只需要使用tf.Variable()传入列表即可
"""
ts_X = tf.Variable([0.4,0.2,0.4])

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X = sess.run(ts_X)
    print(X)

[0.4 0.2 0.4]


In [11]:
"""
2. 查看一维张量
可以使用shape查看数据的形状，因为一维张量共有3个数值，所以显示(3,)
"""
print(X.shape)

(3,)


In [14]:
"""
3. 建立二维张量
建立二维张量也是用tf.Variable()传入二维的列表，所以我们传入的是一个二维数组
"""
ts_X = tf.Variable([[0.4,0.2,0.4]])

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X = sess.run(ts_X)
    print(X)

[[0.4 0.2 0.4]]


In [15]:
"""
4. 查看二维张量，使用shape查看张量的形状
"""
print(X.shape)

(1, 3)


In [17]:
"""
5. 再次建立二维张量
"""
W = tf.Variable([
    [-0.5,-0.2],
    [-0.3,0.4],
    [-0.5,0.2]
])

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    W_array = sess.run(W)
    print(W_array)

[[-0.5 -0.2]
 [-0.3  0.4]
 [-0.5  0.2]]


In [18]:
"""
6. 查看新的二维张量shape
"""
print('shape: ', W_array.shape)

shape:  (3, 2)


## 15.7 矩阵的基本运算

In [20]:
"""
1.矩阵乘法
tf.matmul()， 必须满足矩阵乘法的要求
"""
X = tf.Variable([[1.,1.,1.]])
W = tf.Variable([
    [-0.5,-0.2],
    [-0.3,0.4],
    [-0.5,0.2]
])

XW = tf.matmul(X, W)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print(sess.run(XW))

[[-1.3  0.4]]


In [22]:
"""
2. 矩阵加法
"""
b = tf.Variable([[0.1, 0.2]])
XW = tf.Variable([[-1.3, 0.4]])

Sum = b + XW

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print(sess.run(Sum))

[[-1.1999999  0.6      ]]


In [ ]:
"""
3. 矩阵的乘法和加法
"""